[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    me-no-dev/ESPAsyncWebServer@^3.6.0
    me-no-dev/AsyncTCP@^3.3.2
    bblanchon/ArduinoJson@^7.0.0
board_build.filesystem = SPIFFS
